 ## 数据驱动
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost/all_learning?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
##配置追踪
logging:
  config: classpath:logback-spring.xml

## 文件大小限制
  servlet:
    multipart:
      max-file-size: -1